[package]
name = "tetris"
version = "0.1.0"
authors = ["heropoo <aiyouyou1000@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
#glfw = "0.44.0"
sdl2 = "0.35.2"