name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install libglfw3 libglfw3-dev libglew-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
